apiVersion: v1
kind: Secret
metadata:
  name: civicpulse-secrets
  namespace: civicpulse
type: Opaque
stringData:
  POSTGRES_USER: civicpulse
  POSTGRES_PASSWORD: civicpulse_secret_pw
  POSTGRES_DB: civicpulse_db
  DATABASE_URL: postgresql+asyncpg://civicpulse:civicpulse_secret_pw@postgres-svc:5432/civicpulse_db
  SYNC_DATABASE_URL: postgresql://civicpulse:civicpulse_secret_pw@postgres-svc:5432/civicpulse_db
  REDIS_URL: redis://redis-svc:6379/0
  GROQ_API_KEY: ""
